steps:
  - name: 'gcr.io/k8s-skaffold/pack'
    entrypoint: 'pack'
    args:
      - 'build'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/fitsphere:$COMMIT_SHA'
      - '--builder=gcr.io/buildpacks/builder:v1'
      - '--publish'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'fitsphere'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/fitsphere:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/fitsphere:$COMMIT_SHA'
